### ISSUE TITLE
Unhelpful error message when using `generate` on a MultiSubjectDesign without `subjects_between`, `items_between` and `both_within`

### ISSUE THREAD

**Issue by jschepers** [unfoldtoolbox/UnfoldSim.jl#64]
When creating a MultiSubjectDesign without giving arguments for `subjects_between`, `items_between` and `both_within` (their default is nothing), the `generate` function gives a MethodError as in the following example:
![grafik](https://github.com/unfoldtoolbox/UnfoldSim.jl/assets/22366977/94f9d9b4-60b5-4667-9114-b02b34fca9f6)

The problem originates from the following line in the `generate` function: https://github.com/unfoldtoolbox/UnfoldSim.jl/blob/5e81675d608c729ff1231885df692ef7ce2e520a/src/design.jl#L89

Suggestions:
- Either rewrite the function to make it possible to generate designs without any conditions
- Or handle this case with an appropriate error + message.

**Comment by behinger** [comment]
see also #61 - afaik Judith is setting up to fix it

**Comment by jschepers** [comment]
Solved by #70
