### ISSUE TITLE
renaming

### ISSUE THREAD

**Issue by behinger** [unfoldtoolbox/UnfoldSim.jl#65]
Before 1.0 we should rename a few things:

- `simulate` and `generate` are used in different places, not clear why not same name for everything. Makes sense to me, you can simulate a design, simulate an EEG, simulate noise
- `rand_onsets` actually delivers distances between onsets, `generate(rng,onset,...)` generates the onsets

Let's collect as we go

**Comment by jschepers** [comment]
Remove inconsistency of variable/function naming:
- Examples: `expdesign`, `allconditons` vs. `subject_between`, `both_within` (I would prefer the latter)

**Comment by behinger** [comment]
generate => without "randomess"
simulate => with randomness

**Comment by behinger** [comment]
simulate_noise
simulate_onsets
simulate_epochs
...

**Comment by behinger** [comment]
generate_design

**Comment by behinger** [comment]
this is done in 0.4.0
