### ISSUE TITLE
suggestions

### ISSUE THREAD

**Issue by vladdez** [unfoldtoolbox/UnfoldSim.jl#77]
1. Would be nice to format a code in Home page in docs.
2. It crashed when I entered 8 at σ in `onset = LogNormalOnset(μ = 5, σ = 5.1)`. Extrema parameters should be tested.
3.  [Here](https://unfoldtoolbox.github.io/UnfoldSim.jl/dev/generated/reference/onsettypes/) would be nice to have more spaces in `label = "($μ,$σ,$offset,$truncate_upper)"`. Hard to read
4. DocStrings probably should renamed to API
5. [UnfoldSim.predef_eeg](https://unfoldtoolbox.github.io/UnfoldSim.jl/dev/api/#UnfoldSim.predef_eeg-Tuple{Any}) - this docstring definitely should be check for grammar and formatting.
6. I solved the issue of _ transforming to italic in my docstrings. You can check it here https://github.com/unfoldtoolbox/UnfoldMakie.jl/blob/main/src/docstring_template.jl on string 48
7. UnfoldSim.simulate_component - 4 spaces should be put before a function in doctrings
8. Each docstring should end with a returned value

**Comment by behinger** [comment]
thanks again!

1. fixed in #84 
2. we now throw a warning if simulated onsets are very large in #84
3.  not fixed yet
4. done
5. done
6. done (at least at some places ;))
7. done 
8. havent done that -will create a new issue for it
